import logo from './logo.svg';
import './App.css';

function App() {

  function loop() {
    setTimeout(loop, 1000);
    return "recursion";
  }

  return (
    <div>
      <h1>recursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursionrecursion</h1>
    </div>
  );
}

export default App;
